const ActionType = {
    SIGNIN_INIT: "SIGNIN_INIT",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_FAILED: "SIGNIN_FAILED",

    SIGNUP_INIT: "SIGNUP_INIT",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILED: "SIGNUP_FAILED",

    GET_USERS_INIT: "GET_USERS_INIT",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILED: "GET_USERS_FAILED",

    GET_BOARDS_INIT: "GET_BOARDS_INIT",
    GET_BOARDS_SUCCESS: "GET_BOARDS_SUCCESS",
    GET_BOARDS_FAILED: "GET_BOARDS_FAILED",
}

export default ActionType