const ActionType = {
    SIGNIN_INIT: "SIGNIN_INIT",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_FAILED: "SIGNIN_FAILED",

    SIGNUP_INIT: "SIGNUP_INIT",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILED: "SIGNUP_FAILED",

    SIGNOUT_INIT: "SIGNOUT_INIT",
    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",

    GET_USERS_INIT: "GET_USERS_INIT",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILED: "GET_USERS_FAILED",

    GET_BOARDS_INIT: "GET_BOARDS_INIT",
    GET_BOARDS_SUCCESS: "GET_BOARDS_SUCCESS",
    GET_BOARDS_FAILED: "GET_BOARDS_FAILED",

    GET_BOARD_INIT: "GET_BOARD_INIT",
    GET_BOARD_SUCCESS: "GET_BOARD_SUCCESS",
    GET_BOARD_FAILED: "GET_BOARD_FAILED",

    SAVE_BOARD_INIT: "SAVE_BOARD_INIT",
    SAVE_BOARD_SUCCESS: "SAVE_BOARD_SUCCESS",
    SAVE_BOARD_FAILED : "SAVE_BOARD_FAILED",

    OPEN_BOARD_EDITOR: "OPEN_BOARD_EDITOR",
    CLOSE_BOARD_EDITOR: "CLOSE_BOARD_EDITOR",

    DELETE_BOARD_INIT: "DELETE_BOARD_INIT",
    DELETE_BOARD_SUCCESS: "DELETE_BOARD_SUCCESS",
    DELETE_BOARD_FAILED: "DELETE_BOARD_FAILED",
}

export default ActionType